language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script: ./vendor/bin/tester -s -p php -c ./tests/php.ini-unix ./tests/CarrooiTests/
